
	CREATE DATABASE tagger;
	GRANT ALL PRIVILEGES ON DATABASE tagger TO postgres;
	CREATE DATABASE iotcataloguer;
	GRANT ALL PRIVILEGES ON DATABASE iotcataloguer TO postgres;
	CREATE DATABASE cdpo;
	GRANT ALL PRIVILEGES ON DATABASE cdpo TO postgres;